Version upgrade
CloudSlang/cloudslang-webapp pull request #9
Opened 2021-06-07 13:05 UTC by nehaagarwal1

2021-06-18 06:31 UTC, lucian-cm commented on src/main/resources/security/users.yml
> +      password: password
why change value?

2021-06-18 06:31 UTC, lucian-cm commented on src/main/resources/spring/slangWebappContext.xml
> +    <bean id="queueDispatcher" class="io.cloudslang.engine.queue.services.QueueDispatcherServiceImpl"><aop:scoped-proxy proxy-target-class="false"/> </bean>
why we need proxy-target-class since we have it as well in application.properties?

2021-06-18 06:31 UTC, lucian-cm commented on src/main/resources/bin/win64/webapp.bat
> +java -jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dapp.home="%APP_HOME%" "%APP_HOME%\cloudslang-webapp-0.0.1.jar"
please remove debug port

2021-06-18 06:31 UTC, lucian-cm commented on src/main/java/io/cloudslang/web/security/ApplicationUsers.java
> +@ConfigurationProperties
why location is not working now and we need to manually load users?

2021-06-20 07:45 UTC, nehaagarwal1 commented on src/main/resources/security/users.yml
> +      password: password
reverted ...sorry checked-in by mistake

2021-06-20 07:46 UTC, nehaagarwal1 commented on src/main/resources/bin/win64/webapp.bat
> +java -jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dapp.home="%APP_HOME%" "%APP_HOME%\cloudslang-webapp-0.0.1.jar"
removed it

2021-06-20 07:49 UTC, nehaagarwal1 commented on src/main/java/io/cloudslang/web/security/ApplicationUsers.java
> +@ConfigurationProperties
In Spring Boot 1.4.0 locations property of the @ConfigurationProperties annotation is deprecated and removed after 1.5 so has to make the changes

2021-06-22 14:18 UTC, nehaagarwal1 commented on src/main/resources/spring/slangWebappContext.xml
> +    <bean id="queueDispatcher" class="io.cloudslang.engine.queue.services.QueueDispatcherServiceImpl"><aop:scoped-proxy proxy-target-class="false"/> </bean>
I removed the changes

2021-06-28 10:36 UTC, lucian-cm requested changes

2021-06-28 10:36 UTC, lucian-cm commented on src/main/resources/configuration/log4j2.xml
> +<Configuration>
you are missing the rolling file appender

2021-07-01 09:57 UTC, nehaagarwal1 commented on src/main/resources/configuration/log4j2.xml
> +<Configuration>
fixed it

2021-07-02 14:00 UTC, lucian-cm approved these changes

2021-07-06 07:14 UTC, merged